language: bash

sudo: true

env:
  global:
    - secure: "Qrqjw8L8Mu71b1/Lwtlmyf4EyzG1mGdDKmjAlXy29+JHSdhAskF1iIOaFH2SFHuSxJaGM+k9LNRJYdYAzUqxEH0q4Nmk5YvyKiYUl+5HNX2f+C855hGkE/mMKr0PmEncectpY5t7cYRUR0esbvx7AZyvQHSUDu4cPSzrLPGz2nz6K/040C7NGlma4ck9wsILLHvgSJ5HiZB97yLaVKJUave4Kt6hFag5zaHvEPqISs4b2w/cKVsi35JjIgseYITMUuXoVKMR9EDX1J59NLNV3NG3iPN8+tpZzICpY4j3qY7NitfS5o04sD/hZml938R/0cTgVnNP0jlVE1YfhN95p9F3m187r7zUtqLLN4Tf05nrDbCCZi4g6FKRPnLV3g8zU9lKN3I97kOA3Z+0MCy3R7p5sIUEvthypXK5bcFf8FaCLQKWIFex5//Js3Xg5YPnThSUt2SOXly5DbQ0ctElD52V2xTbbqXMohD08uTqmOdTsVQMOyOXNcK9CqX6AtpafNJ2BQzLy+bbO0Npd/OLkT/4PTrAT33ls0/5ptKSeFsaYjOi/uckGjRSOuAxax1PVZLSJut9iGuWtf8t08nkUZw5vAdFu9RF2f/7YcfKogCAVuWLe2tme35aNjMH1licBQi/MuioM+rT/dhRE1wf7lEKWDGPz7BIfO73npbrJJM="
    - DOCKER_TAG=fermadeiral/test-evolve-bears:latest
    - MERGE_PR_COMMIT_MESSAGE_PATTERN="Merge pull request";
    - NEW_BRANCH_NAME=""

jobs:
  include:
    - stage: Validation - check existence and validity of bears.json file
      if: type = pull_request
      install: ./.travis_bears/install/install_ajv.sh
      script: ./.travis_bears/check_pr/check_bears_json_file.sh;

    - stage: Validation - check existence of mandatory commits and their sequence
      if: type = pull_request
      script: ./.travis_bears/check_pr/check_commits.sh;

    - stage: Validation - check existence of java file in the patched commit
      if: type = pull_request
      script: ./.travis_bears/check_pr/check_existence_java_file.sh;

    - stage: Validation - check existence of build and test log files in the buggy and patched commits
      if: type = pull_request
      script: ./.travis_bears/check_pr/check_existence_of_build_and_test_log_files.sh;

    - stage: Validation - check non-existence of the bug in Bears
      if: type = pull_request
      install: ./.travis_bears/install/install_jq.sh
      script: ./.travis_bears/check_pr/check_if_bug_already_exists.sh;

    - stage: Validation - run tests with Maven on buggy and patched commits
      if: type = pull_request
      services: docker
      script: ./.travis_bears/check_pr/run_check_with_maven.sh 1

    - stage: Validation - run tests with Maven on buggy and patched commits
      if: type = pull_request
      services: docker
      script: ./.travis_bears/check_pr/run_check_with_maven.sh 0

    - stage: Merge
      if: type = push
      install: ./.travis_bears/install/install_jq.sh
      before_script:
        - if [[ "$TRAVIS_COMMIT_MESSAGE" == "$MERGE_PR_COMMIT_MESSAGE_PATTERN"* ]]; then
            git checkout pr-add-bug;
            COMMITTER_USERNAME=$(git log -n 1 --skip 1 --pretty="%cn");
            COMMITTER_EMAIL=$(git log -n 1 --skip 1 --pretty="%ce");
            git config --global user.name "$COMMITTER_USERNAME";
            git config --global user.email "$COMMITTER_EMAIL";
            git config user.name;
            git config user.email;
            git remote add github https://${GH_TOKEN}@github.com/"$TRAVIS_REPO_SLUG".git > /dev/null 2>&1;

            git checkout pr-add-bug;
            repoName=$(jq '.repository.name' bears.json);
            repoName=$(echo "$repoName" | sed -e 's/\"//g');
            repoName=$(echo "$repoName" | sed -e 's/\//-/g');
            buggyBuildId=$(jq '.builds.buggyBuild.id' bears.json);
            fixerBuildId=$(jq '.builds.fixerBuild.id' bears.json);
            NEW_BRANCH_NAME=$repoName-$buggyBuildId-$fixerBuildId;
            echo "Branch to be created - $NEW_BRANCH_NAME";

            git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*;
            git fetch;
          fi
      script:
        - if [[ "$TRAVIS_COMMIT_MESSAGE" == "$MERGE_PR_COMMIT_MESSAGE_PATTERN"* ]]; then
            ./.travis_bears/add_bug/create_new_branch.sh;
          fi
      after_success:
        - if [[ "$TRAVIS_COMMIT_MESSAGE" == "$MERGE_PR_COMMIT_MESSAGE_PATTERN"* ]]; then
            git checkout pr-add-bug;
            ./.travis_bears/add_bug/update_data.sh;
          fi
      after_script:
        - if [[ "$TRAVIS_COMMIT_MESSAGE" == "$MERGE_PR_COMMIT_MESSAGE_PATTERN"* ]]; then
            git stash;
            git checkout pr-add-bug;
            ./.travis_bears/add_bug/reset_pr-add-bug_branch.sh;
          fi

branches:
  - only:
    - pr-add-bug
