language: bash

sudo: true

services:
  - docker

env:
  global:
    - DOCKER_TAG=fermadeiral/test-evolve-bears:latest
    - secure: "Qrqjw8L8Mu71b1/Lwtlmyf4EyzG1mGdDKmjAlXy29+JHSdhAskF1iIOaFH2SFHuSxJaGM+k9LNRJYdYAzUqxEH0q4Nmk5YvyKiYUl+5HNX2f+C855hGkE/mMKr0PmEncectpY5t7cYRUR0esbvx7AZyvQHSUDu4cPSzrLPGz2nz6K/040C7NGlma4ck9wsILLHvgSJ5HiZB97yLaVKJUave4Kt6hFag5zaHvEPqISs4b2w/cKVsi35JjIgseYITMUuXoVKMR9EDX1J59NLNV3NG3iPN8+tpZzICpY4j3qY7NitfS5o04sD/hZml938R/0cTgVnNP0jlVE1YfhN95p9F3m187r7zUtqLLN4Tf05nrDbCCZi4g6FKRPnLV3g8zU9lKN3I97kOA3Z+0MCy3R7p5sIUEvthypXK5bcFf8FaCLQKWIFex5//Js3Xg5YPnThSUt2SOXly5DbQ0ctElD52V2xTbbqXMohD08uTqmOdTsVQMOyOXNcK9CqX6AtpafNJ2BQzLy+bbO0Npd/OLkT/4PTrAT33ls0/5ptKSeFsaYjOi/uckGjRSOuAxax1PVZLSJut9iGuWtf8t08nkUZw5vAdFu9RF2f/7YcfKogCAVuWLe2tme35aNjMH1licBQi/MuioM+rT/dhRE1wf7lEKWDGPz7BIfO73npbrJJM="

install:
  - sudo apt-get update
  - sudo apt-get install jq -y
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g ajv-cli

jobs:
  include:
    - stage: Validation
      name: "Validating PR..."
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            echo "It is a PR.";
            ./check_pr/check_bears_json_file.sh "$TRAVIS_PULL_REQUEST_BRANCH"
          fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            echo "It is a PR.";
            ./check_pr/check_commits.sh "$TRAVIS_PULL_REQUEST_BRANCH"
          fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            echo "It is a PR.";
            docker pull "$DOCKER_TAG";
            docker run --name "$TRAVIS_PULL_REQUEST_BRANCH" --mount type=bind,source="$(pwd)",target=/var/app/pr --env BRANCH_NAME="$TRAVIS_PULL_REQUEST_BRANCH" "$DOCKER_TAG";
            exit $(docker inspect "$TRAVIS_PULL_REQUEST_BRANCH" --format='{{.State.ExitCode}}');
          fi
    - stage: Merge
      name: "Merge PR..."
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            echo "It is a PR.";
          else
            echo "Travis commit message - $TRAVIS_COMMIT_MESSAGE";
            COMMIT_MESSAGE_PATTERN="Merge pull request";
            if [[ "$TRAVIS_COMMIT_MESSAGE" == "$COMMIT_MESSAGE_PATTERN"* ]]; then
              echo "A PR is being merged.";
              git config --global user.name "fermadeiral";
              git config --global user.email fer.madeiral@gmail.com;
              git remote add github https://${GH_TOKEN}@github.com/fermadeiral/test-evolve-bears.git > /dev/null 2>&1;
              git checkout pr-add-bug;
              repoName=$(jq '.repository.name' bears.json);
              repoName=$(echo "$repoName" | sed -e 's/\"//g');
              repoName=$(echo "$repoName" | sed -e 's/\//-/g');
              buggyBuildId=$(jq '.builds.buggyBuild.id' bears.json);
              fixerBuildId=$(jq '.builds.fixerBuild.id' bears.json);
              NEW_BRANCH_NAME=$repoName-$buggyBuildId-$fixerBuildId;
              echo "Branch to be created - $NEW_BRANCH_NAME";
              bugCommitId=$(git log --format=format:%H --grep="Bug commit");
              testCommitId=$(git log --format=format:%H --grep="Changes in the tests");
              patchCommitId=$(git log --format=format:%H --grep="Human patch");
              endCommitId=$(git log --format=format:%H --grep="End of the bug and patch reproduction process");
              git checkout --orphan "$NEW_BRANCH_NAME"; git reset .; git clean -fd;
              git cherry-pick "$bugCommitId";
              git cherry-pick "$testCommitId";
              git cherry-pick "$patchCommitId";
              git cherry-pick "$endCommitId";
              git push github "$NEW_BRANCH_NAME":"$NEW_BRANCH_NAME";
              git checkout pr-add-bug;
              parentsOfMergingCommit=$(git log --pretty=%P -n 1);
              lastCommitBeforeMerging=${parentsOfMergingCommit%' '*};
              git reset --hard "$lastCommitBeforeMerging"; git push -f github pr-add-bug;
            fi
          fi

after_success:
  - echo "Everything is ok."

branches:
  - only:
    - pr-add-bug

